/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yanisoukaci
 */
package TrainSimulator;
public class PhantomCTCGUI extends javax.swing.JFrame {
    TrackModel red, green;
    TrainController tc;
    TC_MAINGUI wc;
    double speed = 0;
    double authority = 0;
    public int numOfBlocks = 10;
    
    /**
     * Creates new form PhantomCTCGUI
     */
    public PhantomCTCGUI() {
        initComponents();
    }
    public double getSpeed(int train_id)
    {
        return speed;
    }
    public double getAuthority(int train_id)
    {
        return authority;
    }
    
    public void setNumOfBlocks(int num){
        //sets the number of blocks
        this.numOfBlocks = num;
    }
    
    public int getNumOfBlocks(){
        return this.numOfBlocks;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        green_line_button = new javax.swing.JRadioButton();
        red_line_button = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        speedVal = new javax.swing.JTextField();
        authorityVal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pushSpeed = new javax.swing.JButton();
        pushAuthority = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        curr_block = new javax.swing.JLabel();
        updateGUI = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        crossBarPresent = new javax.swing.JLabel();
        crossBarStatus = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        green_line_button.setText("Green Line");

        red_line_button.setText("Red Line");

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        speedVal.setText("---");

        authorityVal.setText("---");

        jLabel1.setText("Speed");

        jLabel2.setText("Authority");

        pushSpeed.setText("Push");
        pushSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pushSpeedActionPerformed(evt);
            }
        });

        pushAuthority.setText("Push");
        pushAuthority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pushAuthorityActionPerformed(evt);
            }
        });

        jLabel3.setText("Current Block");

        curr_block.setText("--");

        updateGUI.setText("Update");
        updateGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateGUIActionPerformed(evt);
            }
        });

        jLabel4.setText("Crossing on Block");

        crossBarPresent.setText("----");

        crossBarStatus.setText("----------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(green_line_button)
                            .addComponent(red_line_button, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(authorityVal, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                    .addComponent(speedVal))
                                .addComponent(curr_block, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(crossBarPresent))))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pushSpeed)
                            .addComponent(pushAuthority))
                        .addContainerGap(144, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(updateGUI)
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(crossBarStatus)
                                .addGap(66, 66, 66))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(red_line_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(green_line_button))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(updateGUI))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(speedVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(pushSpeed))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorityVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(pushAuthority))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(curr_block))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(crossBarPresent)
                    .addComponent(crossBarStatus))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int trainStart = 0;
        
        if(red_line_button.isSelected())
        {
            //put train on red line
            red = new TrackModel("red_line.txt", this);
            green = new TrackModel("red_line.txt", this);
            //wc = new TC_MAINGUI(this, red, green);
            wc = new TC_MAINGUI(this, red, green);
            //System.out.println("run");
            tc = new TrainController(red, 1, trainStart);
            
        }
        else if (green_line_button.isSelected())
        {
            //put train on green line
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pushSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pushSpeedActionPerformed
        // TODO add your handling code here:
        speed = Double.parseDouble(speedVal.getText());
    }//GEN-LAST:event_pushSpeedActionPerformed

    private void updateGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateGUIActionPerformed
        // TODO add your handling code here:
        tc.executeGUI();
        wc.trackControllerGUI.refreshBlockInfoDisplay();
    }//GEN-LAST:event_updateGUIActionPerformed

    private void pushAuthorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pushAuthorityActionPerformed
        // TODO add your handling code here:
        authority = Double.parseDouble(authorityVal.getText());
    }//GEN-LAST:event_pushAuthorityActionPerformed
    public void setCrossBarStatus(String s)
    {
        crossBarStatus.setText(s);
    }
    public void setIsCrossBar(String s)
    {
        crossBarPresent.setText(s);
    }
    public void setCurrBlock(int i)
    {
        curr_block.setText(Integer.toString(i));
        //curr_block.setText(Integer.toString(0));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhantomCTCGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhantomCTCGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhantomCTCGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhantomCTCGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhantomCTCGUI().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authorityVal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel crossBarPresent;
    private javax.swing.JLabel crossBarStatus;
    private javax.swing.JLabel curr_block;
    private javax.swing.JRadioButton green_line_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JButton pushAuthority;
    private javax.swing.JButton pushSpeed;
    private javax.swing.JRadioButton red_line_button;
    private javax.swing.JTextField speedVal;
    private javax.swing.JButton updateGUI;
    // End of variables declaration//GEN-END:variables
}
