/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yanisoukaci
 */
package TrainSimulator;
import java.util.*;

public class PhantomCTCGUI extends javax.swing.JFrame {
    TrackModel red, green;
    TrainController tc;
    ArrayList<TrainController> trains = new ArrayList<>();
    ArrayList<TrackController> red_controllers = new ArrayList<>();
    ArrayList<TrackController> green_controllers = new ArrayList<>();
    ArrayList<Switch> switches_r = new ArrayList<>();
    ArrayList<Switch> switches_g = new ArrayList<>();
    ArrayList<Double> speeds = new ArrayList<>();
    ArrayList<Double> authorities = new ArrayList<>();
    TC_MAINGUI wc;
    TimerTask clock;
    Timer timer;
    int counter = 1;
    public int numOfBlocks = 10;
    
    /**
     * Creates new form PhantomCTCGUI
     */
    public PhantomCTCGUI() {
        initComponents();
    }
    public double getSpeed(int train_id)
    {
        return speeds.get(train_id - 1);
    }
    public double getAuthority(int train_id)
    {
        return authorities.get(train_id - 1);
    }
    
    public double getDt()
    {
        return (1/timer_slider.getValue());
    }
    public void setNumOfBlocks(int num){
        //sets the number of blocks
        this.numOfBlocks = num;
    }
    
    public int getNumOfBlocks(){
        return this.numOfBlocks;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        load = new javax.swing.JButton();
        speedVal = new javax.swing.JTextField();
        authorityVal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pushSpeed = new javax.swing.JButton();
        pushAuthority = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        curr_block = new javax.swing.JLabel();
        updateGUI = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        crossBarPresent = new javax.swing.JLabel();
        crossBarStatus = new javax.swing.JLabel();
        pause_button = new javax.swing.JButton();
        timer_slider = new javax.swing.JSlider();
        addTrain = new javax.swing.JButton();
        trainList = new javax.swing.JComboBox();
        switchList = new javax.swing.JComboBox();
        closeSwitch = new javax.swing.JButton();
        openSwitch = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        load.setText("Load");
        load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadActionPerformed(evt);
            }
        });

        speedVal.setText("---");

        authorityVal.setText("---");

        jLabel1.setText("Speed");

        jLabel2.setText("Authority");

        pushSpeed.setText("Push");
        pushSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pushSpeedActionPerformed(evt);
            }
        });

        pushAuthority.setText("Push");
        pushAuthority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pushAuthorityActionPerformed(evt);
            }
        });

        jLabel3.setText("Current Block");

        curr_block.setText("--");

        updateGUI.setText("Start");
        updateGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateGUIActionPerformed(evt);
            }
        });

        jLabel4.setText("Crossing on Block");

        crossBarPresent.setText("----");

        crossBarStatus.setText("----------");

        pause_button.setText("Stop");
        pause_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pause_buttonActionPerformed(evt);
            }
        });

        timer_slider.setMajorTickSpacing(20);
        timer_slider.setMaximum(200);
        timer_slider.setMinimum(1);
        timer_slider.setMinorTickSpacing(1);
        timer_slider.setPaintLabels(true);
        timer_slider.setPaintTicks(true);
        timer_slider.setSnapToTicks(true);
        timer_slider.setValue(5);

        addTrain.setText("Add Train");
        addTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTrainActionPerformed(evt);
            }
        });

        trainList.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        trainList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainListActionPerformed(evt);
            }
        });

        switchList.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        closeSwitch.setText("Close Switch");
        closeSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeSwitchActionPerformed(evt);
            }
        });

        openSwitch.setText("Open Switch");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(crossBarPresent))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(curr_block)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(crossBarStatus)
                                .addGap(54, 54, 54))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(authorityVal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(speedVal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pushSpeed)
                                            .addComponent(pushAuthority))
                                        .addGap(55, 55, 55)
                                        .addComponent(trainList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(closeSwitch))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addTrain)
                            .addComponent(load))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(updateGUI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pause_button))
                            .addComponent(timer_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(switchList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(openSwitch)
                        .addGap(78, 78, 78))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(timer_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateGUI)
                            .addComponent(pause_button)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(load)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addTrain)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(speedVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(pushSpeed)
                    .addComponent(trainList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorityVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(pushAuthority))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(switchList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeSwitch)
                    .addComponent(openSwitch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(curr_block)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(crossBarPresent)
                    .addComponent(crossBarStatus))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadActionPerformed
        // TODO add your handling code here:
        
        
        //put train on red line
        red = new TrackModel("red_line.txt", this);
        green = new TrackModel("red_line.txt", this);
        red_controllers = red.getLineControllers();
        //green_controllers = green.getLineControllers();
        switches_r = red.getSwitchList();
        //switches_g = red.getSwitchList();
        for(Switch s : switches_r)
        {
            switchList.addItem(s);
        }
        speeds.add(25.00);
        authorities.add(25.00);
        wc = new TC_MAINGUI(this, red, green);
        tc = new TrainController(red, counter, 0);
        counter++;
        trains.add(tc);
        red.addTrainToTrack(counter - 1);
        trainList.addItem(tc);
            
    }//GEN-LAST:event_loadActionPerformed

    private void pushSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pushSpeedActionPerformed
        // TODO add your handling code here:
        int x = trainList.getSelectedIndex();
        System.out.println(x);
        speeds.add(x,Double.parseDouble(speedVal.getText()));
    }//GEN-LAST:event_pushSpeedActionPerformed

    private void updateGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateGUIActionPerformed
        // TODO add your handling code here:
        clock = new Clock(this, wc, trains);
        timer = new Timer(false);
        timer.scheduleAtFixedRate(clock, 0, 1000/timer_slider.getValue());
        
    }//GEN-LAST:event_updateGUIActionPerformed

    private void pushAuthorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pushAuthorityActionPerformed
        // TODO add your handling code here:
        int x = trainList.getSelectedIndex();
        System.out.println(x);
        authorities.add(x,Double.parseDouble(authorityVal.getText()));
    }//GEN-LAST:event_pushAuthorityActionPerformed

    private void pause_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pause_buttonActionPerformed
        // TODO add your handling code here:
        timer.cancel();
        timer.purge();
    }//GEN-LAST:event_pause_buttonActionPerformed

    private void addTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTrainActionPerformed
        // TODO add your handling code here:
        speeds.add(25.00);
        authorities.add(25.00);
        tc = new TrainController(red, counter, 0);
        tc.minimalize();
        counter++;
        red.addTrainToTrack(counter - 1);
        trains.add(tc);
        trainList.addItem(tc);
    }//GEN-LAST:event_addTrainActionPerformed

    private void closeSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeSwitchActionPerformed
        // TODO add your handling code here:
        int x = switchList.getSelectedIndex();
        
        
    }//GEN-LAST:event_closeSwitchActionPerformed

    private void trainListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainListActionPerformed
        // TODO add your handling code here:
        int x = trainList.getSelectedIndex();
        for(TrainController t : trains)
        {
            t.minimalize();
        }
        trains.get(x).normalize();
    }//GEN-LAST:event_trainListActionPerformed
    public void setCrossBarStatus(String s)
    {
        crossBarStatus.setText(s);
    }
    public void setIsCrossBar(String s)
    {
        crossBarPresent.setText(s);
    }
    public void setCurrBlock(int i)
    {
        curr_block.setText(Integer.toString(i));
        //curr_block.setText(Integer.toString(0));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhantomCTCGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhantomCTCGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhantomCTCGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhantomCTCGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhantomCTCGUI().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTrain;
    private javax.swing.JTextField authorityVal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton closeSwitch;
    private javax.swing.JLabel crossBarPresent;
    private javax.swing.JLabel crossBarStatus;
    private javax.swing.JLabel curr_block;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JButton load;
    private javax.swing.JButton openSwitch;
    private javax.swing.JButton pause_button;
    private javax.swing.JButton pushAuthority;
    private javax.swing.JButton pushSpeed;
    private javax.swing.JTextField speedVal;
    private javax.swing.JComboBox switchList;
    private javax.swing.JSlider timer_slider;
    private javax.swing.JComboBox trainList;
    private javax.swing.JButton updateGUI;
    // End of variables declaration//GEN-END:variables
}
